name: Elixir Cache
description: Elixir Cache

runs:
  using: composite
  steps:
    - uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
      with:
        path: '**/deps'
        key: cache-elixir-${{ github.workflow }}-${{ github.job }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: cache-elixir-${{ github.workflow }}-${{ github.job }}-
