[workspace]

[package]
name = "ockly"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "ockly"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.29.1"
lazy_static = "1.4.0"
tokio = "1.31.0"
ockam_identity = {path= "../../../../../rust/ockam/ockam_identity"}
ockam_vault = {path= "../../../../../rust/ockam/ockam_vault"}
minicbor = { version = "0.19.0", features = ["alloc", "derive"] }
