name: Elixir

permissions:
  contents: read

on:
  merge_group:
  pull_request:
    paths:
      - '.github/workflows/elixir.yml'
      - '.github/actions/**'
      - '**.ex'
      - '**.exs'
      - '**/mix.lock'
      - '**/priv/**'
      - '**/native/**'
      - '**.rs'
      - '**.toml'
      - '**/Cargo.lock'
      - 'tools/nix/**'
  push:
    paths:
      - '.github/workflows/elixir.yml'
      - '.github/actions/**'
      - '**.ex'
      - '**.exs'
      - '**/mix.lock'
      - '**/priv/**'
      - '**/native/**'
      - '**.rs'
      - '**.toml'
      - '**/Cargo.lock'
      - 'tools/nix/**'
    branches:
      - develop
  schedule:
    # At 1 am.
    - cron: "0 1 * * *"
  workflow_dispatch:
    inputs:
      commit_sha:
        description: Git commit sha, on which, to run this workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint_ockam_vault_software:
    name: Elixir - lint_ockam_vault_software
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_lint_ockam_vault_software

  lint_ockam:
    name: Elixir - lint_ockam
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_lint_ockam

  lint_ockam_kafka:
    name: Elixir - lint_ockam_kafka
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_lint_ockam_kafka

  lint_ockam_services:
    name: Elixir - lint_ockam_services
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_lint_ockam_services

  lint_ockam_metrics:
    name: Elixir - lint_ockam_metrics
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_lint_ockam_metrics

  lint_ockam_healthcheck:
    name: Elixir - lint_ockam_healthcheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_lint_ockam_healthcheck

  lint_ockam_cloud_node:
    name: Elixir - lint_ockam_cloud_node
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_lint_ockam_cloud_node

  build_ockam_vault_software:
    name: Elixir - build_ockam_vault_software
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_build_ockam_vault_software

  build_ockam:
    name: Elixir - build_ockam
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_build_ockam

  build_ockam_kafka:
    name: Elixir - build_ockam_kafka
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_build_ockam_kafka

  build_ockam_services:
    name: Elixir - build_ockam_services
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_build_ockam_services

  build_ockam_metrics:
    name: Elixir - build_ockam_metrics
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_build_ockam_metrics

  build_ockam_healthcheck:
    name: Elixir - build_ockam_healthcheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_build_ockam_healthcheck

  build_ockam_cloud_node:
    name: Elixir - build_ockam_cloud_node
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_build_ockam_cloud_node

  test_ockam_vault_software:
    name: Elixir - test_ockam_vault_software
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/cargo_home_cache
      - uses: ./.github/actions/cargo_target_dir_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_test_ockam_vault_software
      - uses: ./.github/actions/cargo_target_dir_pre_cache

  test_ockam:
    name: Elixir - test_ockam
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_test_ockam

  test_ockam_kafka:
    name: Elixir - test_ockam_kafka
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_test_ockam_kafka

  test_ockam_services:
    name: Elixir - test_ockam_services
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_test_ockam_services

  test_ockam_metrics:
    name: Elixir - test_ockam_metrics
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_test_ockam_metrics

  test_ockam_healthcheck:
    name: Elixir - test_ockam_healthcheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_test_ockam_healthcheck

  test_ockam_cloud_node:
    name: Elixir - test_ockam_cloud_node
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
      - uses: ./.github/actions/nix_cache
      - uses: ./.github/actions/elixir_cache
      - run: nix develop ./tools/nix --ignore-environment --command make elixir_test_ockam_cloud_node
